### ISSUE TITLE
git - Treating files as binary

### ISSUE THREAD

**Issue by bink** [od0x0/7dfps#39]
git should probably treat dim3s XML files as binary, since mergin them is hardly possible should two people make changes and diffs don't really make sense either.
Should they be added to .gitattributes or should we try and see if git can succesfully merge them when two people edit them?

**Comment by od0x0** [comment]
There doesn't seem to be an easy or straightforward way to handle this.  It's probably better to treat them as binary.  If XML were actually human readable and not as complex, we would likely not have this problem.  It'd probably be a better solution entirely to not work on the two at the same time, since the problem is that dim3 files can't be merged at all.

**Comment by bink** [comment]
I guess editing of maps is one of the very few things that git can't help us with. All edits should therefore be coordinated properly and announced/approved on IRC.
I'll edit the git accordingly later.

**Comment by bink** [comment]
I have changed the settings and git now handles XML as binary.
