### ISSUE TITLE
Emergency Scope Slimdown

### ISSUE THREAD

**Issue by od0x0** [od0x0/7dfps#55]
The pipeline for dim3's editor just isn't feasible for me to produce multiple levels in the time I have.  My Sunday barely exists, my Monday is pretty much nonexistent, and the rest of the time will be needed for linking up the weapon scripts, weapon models, weapon sounds, etc, for which I can't guarantee much time either, as this the final week of school before finals.  Dim3's sluggish and rage-worthy pipeline causes map making to take far longer than it needs to be.  I've made tried making maps in Blender then importing to dim3, but dim3 manages to still screw things up, like the scale, the normals, and the textures.  Making levels in the complicated One Gun Survival Run style I described before just isn't going to happen from me, and considering the amount of work needed of the rest of us, I doubt it'll happen from anyone else either.

For Sunday and Monday, I'll improvise one (1) decent length, utterly sadistic level in blender then fight with dim3 to get it in properly.  The level will basically be a rough frame of map geometry with no real details.

I have the feeling that the rest of our ideas are also overly ambitious for the time we have, and the beast we have to slay...

**Comment by bink** [comment]
What's most important is that we get something playable out of this that's fun.
Doesn't have to be long, but I suggest to have at least 3 checkpoints to be able to test all the weapons.
Also 4 difficulty levels: Easy, Medium, Hard, Impossible.
Each simply has different values for the enemy behavior, so that's easy to implement. We do all our balancing for normal, then use *0.8 for easy, *1.5 for hard, *5 for impossible.

Here's a list of assets we would need:
- Corridor Wall/Floor/Ceiling pieces
- Checkpoint piece
- Assault Rifle Model
- Shotgun Model
- Beam Rifle Model
- Small Enemy Model
- Big Enemy Model
- Various particle graphics
- 4 very short (2-3 minutes?) maps with increasing difficulty
- Weapon Scripts
- Enemy Scripts

We should at least have that much, I think, and it's totally doable imho.

Also: We can use some of the time meant for polishing as well and polish after the 7 days. Those deadlines aren't set in stone.
We'll just do whatever we can as quick as we can and concentrate on getting this game out in a playable version on the 15th, then make it sexy later.

**Comment by trianglebutt** [comment]
Oddity I'll make the maps, this is why I asked if you were committed. It is not that difficult. I'll finish the assets today and Kurton and I can do it.
