### ISSUE TITLE
Model - Item Pickups

### ISSUE THREAD

**Issue by trianglebutt** [od0x0/7dfps#60]
- Weapon crates
- Health crates
- Health cannisters
- Armor fragments
- Steroids

**Comment by bink** [comment]
For the weapons, we should just use the weapon models and make them interactable with a pick up icon. When clicked you throw away your current weapon (can be picked up again) and pick up the new one.

**Comment by trianglebutt** [comment]
I already made weapon crates so NO. :P

**Comment by od0x0** [comment]
Yeah, weapon crates.  Weapon models introduce complications in how they're aligned and how they're resized (because the scale is different for weapon models on screen to weapon models in the map).  However, clicking to pick up is a good idea, as it makes sure the player really wants to do a weapon change.

**Comment by bink** [comment]
Guess we'll use a shitty system from the 90s then that looks really bad instead of what modern games do and what makes sense. 9_9

**Comment by od0x0** [comment]
If we had time, it'd be nice, but we don't have time and there are bigger things to handle. :(

**Comment by bink** [comment]
So can we do it after 7dfps? :3
